version: '3.6'
services:
  dockerauth:
    image: cesanta/docker_auth:1
    container_name: auth
    ports:
      - "5001:5001"
    volumes:
      - /zfsdata/config:/config:ro
      - /zfsdata/logs:/logs
      - /zfsdata/certs:/certs
    command: /config/auth_config.yml
    restart: always